- src/dvc_render/base.py
- src/dvc_render/vega.py
- tests/test_image.py
- tests/test_vega.py
Related: iterative/vscode-dvc#1520
> renderers: test empty values

- setup.cfg
Seems like lack of bump was the reason of failing release build.
https://github.com/iterative/dvc-render/actions/runs/2226819138
> version: bump to 0.0.5

- src/dvc_render/vega_templates.py
Introducing interactivity to confusion matrix.
[example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoJFEwMdaEFEFIIEAPoBGRSABmNQXFlIEcK1ByblIy8ko4AE5wyjRm0QG29s6uUcRWAO5sEQDWEDimcKiogbLB0nIgAL4KJmYWggl2ji5KHl4+fgFBIRXhUTFxyo1JLSCpGVm5+VCFxd3l8tW15pboNk3JrZ7evv5r86GukdGxmPFriY4ATClwaeiZOXkFRSVlh0sgpisNFxs3W3auy6pR6YRAxwGZyGfxGt3uIEeUxec1BCyqNS+dVW1kuDgB7m2HT21gOvQh-VO51x-3hEye01mbzBGOW9WGzVcbR2nX2aMOfROgw5+Lp6AAEgBRACCABFXmTFpjvuzYZzATyScz0YKodT1kkCeMJTL5aj3hVPiqcQb1YSgbzSfzyZCqTCaYaxSApXKFc6lWybXiCdziSCLeDXcK1ZsxncrD6zdqPsrsb8PdcuUTgXyI0dKdGM7Hjd7TX685UALrVECYOheKzKYhQSgAT18gnLLNaBUwaFAHjggnd4yUmFbOBJsjYCBoPgaNbycCg-drESQsggbiyCCMJjIZCiFDOe5AbBwXQYsj7SjsVgAHq2HIEr32q0pD2wGDgmK2jBShWh …
> vega: templates: make confusion matrix interactive

- .github/workflows/release.yml
- .github/workflows/tests.yml
- pyproject.toml
- setup.cfg
See https://github.com/iterative/py-template/pull/17.
I haven't bumped the cruft commit because there are some changes that are related to docs, which I was not sure how to fix.
> cruft updates: force nox color, single workflow run and setuptools_scm for versioning

- src/dvc_render/vega_templates.py
In previous change (#45) I hardcoded the fields name. Fixing it here
> confusion matrix: fix hardcoded values

- src/dvc_render/vega.py
Hello,
I wanted to create bar-plots for DVC and to be able to diff these I use the xOffset parameter in vega-lite. This was added in the 5.2.0 release of vega-lite.
For an example of the bar plots, see: https://github.com/daniel-falk/dvc-examples
I am not sure how to build DVC with this updated version of dvc-render, so I have not tested it other than with the custom html template in the repo linked above.
> Upgrade vega-lite to 5.2.0

- src/dvc_render/html.py
- tests/test_html.py
This is a PR to fix the issue #58.
I am unsure of the usefulness of the test case added, please let me know it that seems sensible.
The templating should now be resilient against unexpected template strings.
> fix issue #58

- src/dvc_render/vega_templates.py
#8 Solved by this.
However, I think this is not ideal in the long run if more templates appear. The two new templates are almost identical. One could do a hotfix like this for the `BarHorizontalSorted` class:
```
DEFAULT_CONTENT = copy.deepcopy(BarHorizontalTemplate.DEFAULT_CONTENT)
DEFAULT_CONTENT["encoding"]["y"]["sort"] = "-x"
```
but that is quite ugly. I guess it would make sense to add optional parameters and a bit more hierarchy to the plots later if there are many variants of almost the same templates.
Also, not up to me but `vega_templates.py` is already fairly long and it might make sense to put the template class definitions into separate `.py` files.
> Bar chart template

- pyproject.toml
- setup.cfg
- src/dvc_render/base.py
- src/dvc_render/exceptions.py
- src/dvc_render/html.py
- src/dvc_render/image.py
- src/dvc_render/markdown.py
- src/dvc_render/plotly.py
- src/dvc_render/table.py
- src/dvc_render/utils.py
- src/dvc_render/vega.py
- tests/test_image.py
- tests/test_markdown.py
- tests/test_table.py
- tests/test_vega.py
Cutting quite a few corners to cover the minimum for https://github.com/iterative/dvclive/issues/91
Proper refactor would make sense as follow-up because the whole package was focused on a single output format (HTML).
---
table: Add `generate_markdown`.
image: Add `generate_markdown`.
vega: Add `generate_markdown`.
"Translate" vega plot to `matplotlib` figure to save as `png`.
Introduce `render_markdown`.
Closes #62
> Add `markdown` support.

- src/dvc_render/plotly.py
- tests/test_parallel_coordinates.py
DVC passes some values as `rich.Text` instead of string.
As an oversight in #69 , the refactor to use `list_dict_to_dict_list` removed this string casting, breaking `dvc exp show --pcp`
> plotly: Add missing cast to str for rich.Text conversion.

- src/dvc_render/vega.py
- src/dvc_render/vega_templates.py
- tests/test_templates.py
- tests/test_vega.py
> vega: Escape special characters in `field` and `title`.

- src/dvc_render/vega.py
- tests/test_vega.py
Unnecesary escaping for `title` and labels was added in #81.
> vega: Only escape `field`.

- src/dvc_render/markdown.py
- src/dvc_render/table.py
Using 2 Tablerenderers sequantially breaks the first one unless the new line is introduced.
Before:
```
params.yaml
|   foobar |
|----------|
|        0 |
dvclive.json
|   step |   foo |
|--------|-------|
|      0 |     1 |
```
After:
```
params.yaml
|   foobar |
|----------|
|        0 |
dvclive.json
|   step |   foo |
|--------|-------|
|      0 |     1 |
```
> TableRenderer: Include first new line.

- src/dvc_render/vega_templates.py
- tests/test_templates.py
Replace `rglob` with exact matching. Fixes potential bug from using `rglob({template_name}*)`
Per https://github.com/iterative/studio/pull/4504
> templates: Add optional `fs` arg.

- src/dvc_render/vega_templates.py
Fixes https://github.com/iterative/vscode-dvc/pull/3132
`--json` returns data points in a slightly different format compared to the regular `--show-vega` (which is how DVC renders it I think):
```json
{
"precision": 0.3043014798093805,
"recall": 1,
"threshold": 0.00033803811731466854,
"dvc_data_version_info": {
"filename": "eval/prc/train.json",
"field": "precision"
},
"filename": "eval/prc/train.json",
"field": "precision",
"rev": "try-large-dataset"
}
```
vs
```json
{
"precision": 0.30396793085089724,
"recall": 1.0,
"rev": "<rev>:eval/prc/train.json",
"threshold": 0.00022598870056497175
}
```
`transform` applied in the `smooth` template was grouping points by `rev` only, which was fine in a regular case since `rev` field include both `rev` _and_ file name for flexible plots. Not enough …
> Update smooth template: default tooltip, group by filename

- src/dvc_render/vega_templates.py
- tests/test_vega.py
This does complicate the template, but there were a few things bothering me playing around with the `smooth` template that are fixed here:
1. Extra fields like `thresholds` are now shown in the tooltip.
2. Smoothing impacts only the line, not the points (if you search for loess smoothing, this is more common, and it allows you to simultaneously see the trend and the actual values of the points).
3. 💅 Because of the combination of values of the min, default, and step values, the slider would always get stuck on odd values (for example, it would max out at 0.991).
> minor changes to smooth template

- src/dvc_render/vega_templates.py
See https://github.com/iterative/dvc-render/issues/115. #113 moved the legend to the top, but it caused more problems than it solved, and VS Code at least will still use the legend to the right. Doing the same here ensures consistency across products.
> revert fixing legend to top

- src/dvc_render/html.py
- tests/test_html.py
Will be used in DVCLive for https://github.com/iterative/dvclive/issues/460
> html: Support passing custom_template as string.

- src/dvc_render/vega_templates.py
Way back in https://github.com/iterative/dvc/pull/4975, tooltip-like functionality was added to the scatter template. Instead of `tooltip`, it is implemented in some much more complex logic. I don't know why; maybe it wasn't supported yet in vega-lite. Anyway, there doesn't seem to be any other justification for the complexity of the template, so this replaces all of that extra logic with `tooltip`.
Also, we were already using a scatter plot with jitter to show overlapping points easier in https://github.com/iterative/vscode-dvc-demo. This contributes it back as a built-in `scatter_jitter` template.
> Simplifies `scatter` and adds `scatter_jitter` template

- src/dvc_render/vega.py
- tests/test_vega.py
`0.3.0` release broke `dvc plots --json` for older DVC installations because `dvc-render` dep didn't had an upper bound.
> vega: Add `as_string` argument. Default True.

- src/dvc_render/vega_templates.py
Related to https://iterativeai.slack.com/archives/C01SR9Q12LB/p1681991760838949?thread_ts=1681958116.002649&cid=C01SR9Q12LB
Before: 
After: 
Doesn't necessarily look better for this example, but generally I think it will work better to have the values in the tooltip for anything beyond binary classification.
> move confusion matrix text to tooltip

- src/dvc_render/image.py
- src/dvc_render/markdown.py
- src/dvc_render/vega.py
- tests/test_image.py
- tests/test_markdown.py
- tests/test_vega.py
To support markdown reports in notebooks without needing to source from external files
> add base64 support for markdown

- src/dvc_render/vega_templates.py
- tests/test_templates.py
Before this PR, if I include the `<DVC_METRIC_DATA>` anchor in a custom template within a list, I would get this:
```
$ dvc plots show
ERROR: unexpected error - Template 'vega_linear.json' is not using '<DVC_METRIC_DATA>' anchor
```
Found this when trying out a vega (not vega-lite) template. Even though we don't support vega, it still seems like a bug, and vega actually works after this PR, at least for the [simple example](https://github.com/dberenbaum/vscode-dvc-demo/blob/vega/vega_linear.json) I tried.
> allow for data anchor to be found in list

- src/dvc_render/vega_templates.py
- tests/test_templates.py
- tests/test_vega.py
Previously, the way in which lists were parsed from dvc templates caused the `dict_find_value` function to end early without continuing to parse the rest of the template once it encountered a list. Additionally, the structure of vega-lite plots when using lists allows for the case of a list of strings. Because of this, when called recursively as was done in https://github.com/iterative/dvc-render/commit/635eaff2784f84302f9d354f763276740da246f3 , the function may fail when it encounters something like a list of strings, as it tries to access the values of d, which is no longer a dictionary, but a string. I have fixed this by allowing for `d` to be a string, but this may not be desired/sensible since the function is called `dict_find_value`. It may make sense to change the name of the …
> Modified recursive dictionary parsing to correctly handle lists in dvc plot templates

- src/dvc_render/html.py
- tests/test_html.py
Discovered this one whilst working on https://github.com/iterative/dvc/issues/9940
This PR fixes a bug in the HTML. Previously "image per step" images where not ordered correctly due to their paths being treated as strings.
https://github.com/iterative/dvc-render/assets/37993418/ee7ba131-16df-43fb-a000-b214c09075d0
https://github.com/iterative/dvc-render/assets/37993418/0a4335f8-d515-4082-a7a6-9ad1cc5df1bc
Note: don't ask for a slider.
> Order image per step plots

- src/dvc_render/vega.py
- src/dvc_render/vega_templates.py
- tests/test_vega.py
Closes https://github.com/iterative/dvc-render/issues/28
This PR makes it possible for users to add anchors into strings for calculation purposes in custom templates.
Note: As this is close to a 1 line change and is non-breaking it makes more sense to split it out from #142.
> Fill template anchors inside custom template strings

- src/dvc_render/vega_templates.py
Closes:
* https://github.com/iterative/vscode-dvc/issues/4670
* https://github.com/iterative/dvc.org/issues/4866
After looking into this briefly, it was less work and more useful to add a toggle to turn text on or off.
Demo:
https://github.com/iterative/dvc-render/assets/2308172/d2cf7056-9519-4a06-8aea-6fba98a33df7
> toggle confusion matrix text

- src/dvc_render/base.py
- src/dvc_render/image.py
- src/dvc_render/table.py
Accidental regression from #144
> keep consistent generate_markdown signature

- pyproject.toml
- src/dvc_render/vega.py
- tests/test_vega.py
Closes https://github.com/iterative/dvc-render/issues/149
> patch revs_with_datapoints not being provided

- pyproject.toml
- src/dvc_render/vega_templates.py
- tests/test_vega.py
See https://github.com/iterative/studio/issues/8851
Averages over groupby instead of summing, so that if there are multiple values within each group, we don't end up with unexpectedly large values (for example, >1 values in an ROC plot).
Before this PR:
https://github.com/iterative/dvc-render/assets/2308172/40426951-4508-4029-b966-538afcadfb0a
After this PR:
https://github.com/iterative/dvc-render/assets/2308172/58dcc517-b27f-412b-9fa5-375b3c6008a2
> Groupby mean

- src/dvc_render/vega_templates.py
I've fixed the alignment of the confusion matrix title to be centered. Before, it was left-aligned which wasn't consistent with other plots – and IMO doesn't look nice.
| Before | After |
| - | - |
| ![before](https://github.com/iterative/dvc-render/assets/2206639/9aede562-aaf8-447c-8a9e-04a134026f75) | ![after](https://github.com/iterative/dvc-render/assets/2206639/af516777-1fc0-40b8-972e-454e4ad4dfd3) |
> center-align confusion matrix title
